name: docker build push

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image for FastAPI
        run: docker build -t '${{ secrets.DOCKER_USERNAME }}'/companypluspy:'${{github.sha}}' .

      - name: Log in to the Docker Hub registry
        run: docker login --username '${{ secrets.DOCKER_USERNAME }}' --password '${{ secrets.DOCKER_PASSWORD }}'

      - name: Push the Docker image to Docker Hub
        run: docker push '${{ secrets.DOCKER_USERNAME }}'/companypluspy:'${{github.sha}}'
